/*
 * TopwayCmdList.h
 *
 *  Created on: Oct 14, 2025
 *      Author: VenkateshArikanti
 */
//List of commands codes for Topway LCD module.

#ifndef TOPWAYCMDLIST_H_
#define TOPWAYCMDLIST_H_

#define	TOPWAY_HANDSHAKE_CMD				0x30
#define TOPWAY_READ_VERSION_CMD				0x31
#define TOPWAY_READ_PAGEID_CMD				0x32
#define TOPWAY_TOUCH_RELEASE_COORD_EVENT	0x72
#define TOPWAY_TOUCH_DOWN_COORD_EVENT		0x73
#define TOPWAY_TOUCH_RELEASE_KEYID_EVENT	0x78
#define TOPWAY_TOUCH_DOWN_KEYID_EVENT		0x79
#define TOPWAY_TOUCH_VP_ADDR_VALUE_EVENT	0x77
#define TOPWAY_SET_SYSCONFIG_CMD			0xE0
#define TOPWAY_SET_PROJECT_CMD				0xE1
#define TOPWAY_TOUCH_CALIB_CMD				0xE4
#define TOPWAY_SCREEN_SAVER_CMD				0x5E
#define TOPWAY_BACKLIGHT_CTRL_CMD			0x5F
#define TOPWAY_BUZZER_TOUCH_SOUND_CMD		0x79
#define TOPWAY_BUZZER_CTRL_CMD				0x7A
#define TOPWAY_FLASH_WRITE_CMD				0x90
#define TOPWAY_FLASH_READ	_CMD			0x91
#define TOPWAY_RTC_READ_CMD					0x9B
#define TOPWAY_RTC_SET_CMD					0x9C
#define TOPWAY_USER_PIN_READ_CMD			0x93
#define TOPWAY_U_DRV_FORMAT_CMD				0xE2
#define TOPWAY_U_DRV_UNLOCK_CMD				0xE3
#define TOPWAY_LOAD_PAGE_CMD				0x70
#define TOPWAY_SET_ELEMENT_FG_CMD			0x7E
#define TOPWAY_SET_ELEMENT_BG_CMD			0x7F
#define TOPWAY_SET_CODE_PAGE_CMD			0xE7  // Char set cmd for country
#define TOPWAY_SUSPEND_VP_FRESH_CMD			0xE8
#define TOPWAY_SUCCESSIVE_WRITE_CMD			0x82
#define TOPWAY_SUCCESSIVE_READ_CMD			0x83
#define TOPWAY_VP_BACKUP_CMD				0x94
#define TOPWAY_VP_PRELOAD_CMD				0x95
#define TOPWAY_BP1_WRITE_CMD				0x4B
#define TOPWAY_BP1_WRITE_COMP_CMD			0x4C
#define TOPWAY_G16_WRITE_CMD				0x4D
#define TOPWAY_G16_WRITE_ROTATE_CMD			0x4E
#define TOPWAY_REG_WRITE_CMD				0x3B
#define TOPWAY_REG_READ_CMD					0x3C
#define TOPWAY_STR_WRITE_CMD				0x42
#define TOPWAY_STR_READ_CMD					0x43
#define TOPWAY_STR_FILL_CMD					0x46
#define TOPWAY_N16_WRITE_CMD				0x3D
#define TOPWAY_N16_READ_CMD					0x3E
#define TOPWAY_N16_FILL_CMD					0x3F
#define TOPWAY_N32_WRITE_CMD				0x44
#define TOPWAY_N32_READ_CMD					0x45
#define TOPWAY_N32_FILL_CMD					0x47
#define TOPWAY_N64_WRITE_CMD				0x48
#define TOPWAY_N64_READ_CMD					0x49
#define TOPWAY_N64_FILL_CMD					0x4A


#endif /* TOPWAYCMDLIST_H_ */
